const String defaultDatabaseUrl = 'https://ehwqccznlwnxscpzuhuh.supabase.co';
const String defaultDatabasePKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVod3FjY3pubHdueHNjcHp1aHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzA4Mzk1NTAsImV4cCI6MTk4NjQxNTU1MH0.-6lql0PFwrAqOAbaU9XVx9K2jqrE16vyz-9mHRGUn4E';
