name: forgottenlandapp_adapters
description: Forgotten Land App adapters
version: 25.09.30+1
publish_to: none

environment:
  sdk: "3.6.0"

dependencies:
  forgottenlandapp_utils:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-utils"
      ref: master
  dio: ^5.1.1
  postgrest: ^2.4.2
  supabase: ^2.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
